### ISSUE TITLE
Missing dependencies in src/services

### ISSUE THREAD

**Issue by aforty** [olofd/react-native-insta-photo-studio#3]
1. Looks like there is a dependency on `react-native-photos-framework` but it's looking for it in the project root as opposed to a separate module provided by npm. Not sure if this was intentional or not but the end result is that the package does not currently work when dropped into a project.

2. Also missing is what appears to be an extended `event-emitter` (one that declares a `onAlbumAssetServiceChanged` method?) also expected to be in the root.

`src/services/camera-roll-service.js` is an example that looks for both dependencies.

3. I also had to add the following packages, so they should probably just be defined as dependencies in package.json: `moment-duration-format` and `react-native-video`

There might be more missing dependencies but this is as far as I got. I'd try to clone this git repo into a sample project and try to run it, you'll probably come across the rest.

Also as I started debugging these issues I noticed the absolute breathtaking amount of work that has gone into this project. Kudos and congratulations are in order on just getting to this point. I can't wait to play around with it and add PR's.

**Comment by olofd** [comment]
Yes. Will fix all of this when I go though the app tonight. Will make it able to install on a fresh RN-project.

**Comment by aforty** [comment]
I guess I jumped the gun a little by installing before it was really ready. Just assumed it would be by your release announcement on reddit. Anyway, can't wait!

**Comment by olofd** [comment]
😄  No problems at all. Did not really think it though when I uploaded the video. Will make it installable asap!

**Comment by olofd** [comment]
I think I've fixed it. It's not perfect but should work. >Try running `npm i react-native-insta-photo-studio --save` in your project now and see if it works. Published a new version on npm called 0.1.0

**Comment by aforty** [comment]
Yep it's working now. Very cool!
