### ISSUE TITLE
Doesnt compile on Linux

### ISSUE THREAD

**Issue by hugows** [olofd/react-native-insta-photo-studio#4]
After installing a few dependencies that seemed to be missing:

2003  npm install --save glob
 2010  npm install --save xmldoc
 2012  npm install --save npmlog
 2014  npm install --save chalk
 2016  npm install --save xcode
 

That last one seems to be OSX specific :(

**Comment by olofd** [comment]
@hugows Ah. Did you clone the repository and run npm install in the cloned repo?
That would yeild this error. I've not made the project run fully when being cloned (The example proj) yet. I've only made it possible to install the component as a third party dependency to your own app.

If that's the issue, I'll fix it later today.

**Comment by olofd** [comment]
Sry again. did not read your title. No, @hugows, this currently needs OS X. The component currently only runs on iOS and not android. Is working on a few issues on the android side. Taking care of this issue is one of them.

**Comment by hugows** [comment]
Ok, thanks for the explanation!
